### ISSUE TITLE
Question: How to debug route53 error

### ISSUE THREAD

**Issue by Pindar** [majorleaguesoccer/go-route53-presence#1]
First, thank you for sharing your code. I tried it but I'm getting the following error:

> Error registering instance IP address with Route53 Type: Sender, Code: InvalidInput, Message: Invalid request

I'm setting ROUTE53_RECORD_NAME=foobar.local., ROUTE53_RECORD_TYPE=A, ROUTE53_ZONE_ID=MY_ZONE and the amazon keys.
Do you have any idea how to debug it further? 

Update:
I found out that AliasTarget is in the request:

```xml
<AliasTarget>
                  <HostedZoneId />
                  <DNSName />
                  <EvaluateTargetHealth>false</EvaluateTargetHealth>
               </AliasTarget>
```

**Comment by Pindar** [comment]
I close this ticket because it's caused by a new commit in the goamz project which is referenced.

**Comment by brycekahle** [comment]
@Pindar to avoid issues like this we vendored the dependencies. Take a look at the `godep` tool.

**Comment by brycekahle** [comment]
There are also images for this on docker hub that you can use without rebuilding. https://registry.hub.docker.com/u/majorleaguesoccer/go-route53-presence/

**Comment by Pindar** [comment]
@brycekahle thank you for your reply! I found it out in the end and got it working - just didn't thought that the framework is broken.

Other then that it's working perfectly fine - I love this idea of a totally moving infrastructure
